name: gmpay
description: Fast and secure transactions for businesses and individuals.
version: 1.0.26
homepage: https://github.com/Fanom2813/gmpay

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  deep_pick: ^1.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  http: ^1.2.2
  shimmer_animation: ^2.2.1
  url_launcher: ^6.3.0
  wolt_modal_sheet: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/